config/routes.rb
Rails.application.routes.draw do
  get '/about' ,to: 'pages#about_us'
  get '/contact' ,to: 'pages#contact_us'
  get '/privacy' ,to: 'pages#privacy_policy'
  get '/terms_and_conditions' ,to: 'pages#terms_and_conditions'
  # get '/home/index' ,to: 'home#index'
  root "home#index"

  resource :session
  resource :registration
  resource :password_reset
  resource :password 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current< ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    before_save :mail_downcase

    validates :email, presence: true

    def mail_downcase
        if email.present?
            email.downcase!
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def current_user
        Current.user ||= authenticate_user_from_session
    end
    helper_method :current_user
    
    def authenticate_user_from_session
        User.find_by(id: session[:user_id])
    end

    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?

    def login(user)
        Current.user = user
        reset_session
        session[:user_id] = user.id
    end

    def logout(user)
        Current.user = nil
        reset_session
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end

  def contact_us
  end

  def privacy_policy
  end

  def terms_and_conditions
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(registration_params)
        if @user.save
            login @user
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    private

    def registration_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/index.html.erb
<h1>Hello World!!</h1>

<%= render 'shared/links' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HrMitra</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>

    <div><%= notice %></div>
    <div><%= alert %></div>

    <% if user_signed_in? %>
      <%= link_to 'Edit password', edit_password_path %>
      <%= button_to "Log Out", session_path, method: :delete %>
      <% else %>
      <%= link_to "Sign Up", new_registration_path %>
      <%= link_to "Log in", new_session_path %>
    <% end %>
      

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

app/views/pages/about_us.html.erb
<h1>Pages#about_us</h1>
<p>Find me in app/views/pages/about_us.html.erb</p>

<%= render 'shared/links' %>

app/views/pages/contact_us.html.erb
<h1>Pages#contact_us</h1>
<p>Find me in app/views/pages/contact_us.html.erb</p>

<%= render 'shared/links' %>

app/views/pages/privacy_policy.html.erb
<h1>Pages#privacy_policy</h1>
<p>Find me in app/views/pages/privacy_policy.html.erb</p>


<%= render 'shared/links' %>

app/views/pages/terms_and_conditions.html.erb
<h1>Pages#terms_and_conditions</h1>
<p>Find me in app/views/pages/terms_and_conditions.html.erb</p>


<%= render 'shared/links' %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-danger">
  <div class="container-fluid">
    <%= link_to "HR-Mitra", root_path , class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About Us', about_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contact Us', contact_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Privacy Policy', privacy_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Terms and Conditions', terms_and_conditions_path, class: "nav-link"  %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_links.html.erb
<h1>HR Mitra</h1>
<%= link_to 'About_us', about_path, target: '_blank', style:'color: red;'%>
<%= link_to 'Contact', contact_path, target: '_blank', style:'color: red;'%>
<%= link_to 'Privacy', privacy_path, target: '_blank', style:'color: red;'%>
<%= link_to 'Terms And Conditions', terms_and_conditions_path, target: '_blank', style:'color: red;'%>